CLASSPATHS=lib/htmlparser.jar:lib/servlet-api.jar:lib/junit-4.5.jar:lib/log4j-1.2.15.jar
JFLAGS = -g -classpath $(CLASSPATHS)
JC = javac
CLASSES = ./src/files/IApilable.java ./src/files/AbstractFile.java ./src/files/SecuencialFile.java ./src/files/File.java ./src/files/StackFile.java ./src/persistors/Persistor.java ./src/persistors/StringPersistor.java ./src/persistors/AbstractPersistor.java ./src/persistors/IntegerPersistor.java ./src/persistors/BytePersistor.java ./src/exceptions/BusinessException.java ./src/exceptions/DataAccessException.java ./src/api/ObjectFactory.java ./src/ControllerServlet.java ./src/test.java ./src/SecuentialFileTest.java ./src/FileTest.java ./src/StackFileTest.java
classes:
	$(JC) $(JFLAGS) $(CLASSES)
clean:
	   rm $(find -name '*.class')

./src/files/IApilable.class: ./src/files/IApilable.java
		$(JC) $(JFLAGS) $*.java
./src/files/AbstractFile.class: ./src/files/AbstractFile.java
		$(JC) $(JFLAGS) $*.java
./src/files/SecuencialFile.class: ./src/files/SecuencialFile.java
		$(JC) $(JFLAGS) $*.java
./src/files/File.class: ./src/files/File.java
		$(JC) $(JFLAGS) $*.java
./src/files/StackFile.class: ./src/files/StackFile.java
		$(JC) $(JFLAGS) $*.java
./src/persistors/Persistor.class: ./src/persistors/Persistor.java
		$(JC) $(JFLAGS) $*.java
./src/persistors/StringPersistor.class: ./src/persistors/StringPersistor.java
		$(JC) $(JFLAGS) $*.java
./src/persistors/AbstractPersistor.class: ./src/persistors/AbstractPersistor.java
		$(JC) $(JFLAGS) $*.java
./src/persistors/IntegerPersistor.class: ./src/persistors/IntegerPersistor.java
		$(JC) $(JFLAGS) $*.java
./src/persistors/BytePersistor.class: ./src/persistors/BytePersistor.java
		$(JC) $(JFLAGS) $*.java
./src/exceptions/BusinessException.class: ./src/exceptions/BusinessException.java
		$(JC) $(JFLAGS) $*.java
./src/exceptions/DataAccessException.class: ./src/exceptions/DataAccessException.java
		$(JC) $(JFLAGS) $*.java
./src/api/ObjectFactory.class: ./src/api/ObjectFactory.java
		$(JC) $(JFLAGS) $*.java
./src/ControllerServlet.class: ./src/ControllerServlet.java
		$(JC) $(JFLAGS) $*.java
./src/test.class: ./src/test.java
		$(JC) $(JFLAGS) $*.java
./src/SecuentialFileTest.class: ./src/SecuentialFileTest.java
		$(JC) $(JFLAGS) $*.java
./src/FileTest.class: ./src/FileTest.java
		$(JC) $(JFLAGS) $*.java
./src/StackFileTest.class: ./src/StackFileTest.java
		$(JC) $(JFLAGS) $*.java


